#!/bin/bash

git clone $1
PRJ_NAME=$(basename $1 .git)
cd $PRJ_NAME
npm i

./commit $1 initial commit 💢
git checkout -b staging
git push -u origin staging
git checkout -b develop
git push -u origin develop